# Generated by Django 4.2.7 on 2025-08-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
