# Generated by Django 4.2.7 on 2025-08-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
